# _config.yml

# URL base do seu site (importante para o GitHub Pages)
# Substitua "nome-do-seu-repositorio" pelo nome do seu repositório
baseurl: "/meu-portfolio" 

# URL completa do seu site
# Substitua "seu-usuario" pelo seu nome de usuário do GitHub
url: "https://github.com/JessyTeixeira-QA"

# Outras configurações do Jekyll podem vir aqui
# Exemplo:
title: Meu Portfólio
description: Portfólio de Jessica Ferreira Teixeira
